# Change these first
owner: micway # Your GitHub organization or username, where this repository lives
repo: healthcheck # The name of this repository

sites:
  - name: PALLET LOADER API
    url: $PALLET_LOADER_API_PROD_HEALTH_URL
    headers:
    - "x-functions-key: $PALLET_LOADER_API_PROD_KEY"
  - name: OUTLOOK
    url: https://outlook.office365.com/owa/
  - name: MICROSOFT AUTHENTICATION
    url: https://login.microsoftonline.com
    headers:
    - "User-Agent: Micway-HealthCheck"
  - name: OFFICE 365
    url: https://graph.microsoft.com
  - name: AZURE
    url: https://azure.status.microsoft
  - name: GOOGLE
    url: https://www.google.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.micway.com.au
  # baseUrl: /healthcheck
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Micway Services Status
  # introTitle: ""
  introMessage: "Here you'll find real-time updates on the health of the Micway applications, APIs, databases, Outlook integration, and more. We monitor everything 24/7 to keep your experience smooth and reliable."
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
